### ISSUE TITLE
Externí vyvolání pořadu a řazení

### ISSUE THREAD

**Issue by dimov-cz** [waladir/plugin.video.ivysilani.cz#3]
Zdravím,

díky za resuscitaci tohohle užitečného doplňku. Doplněk funguje zatím hladce a v moha věcech je i příjemnější než dřív. 

### Spuštění pořadu z Android aplikace 
Existuje na to teď nějáká cesta? Já teda jednu dřív našel, ale od posledních změn už to nejde. Fungovalo to takto:

- V mobilu aplikace iVysilani, najdu pořad a dám sdílet
- Kore se tam nenabídne, ale nabídne se Yatse (takže v mobilu mám i Yatse ve free verzi)
- V kodi pomocný script od Yatse - ten sám o sobě nestačí, přidal jsem si do něj zachycení url ivysilani, vyparsoval poslední ID (id pořadu nebo dílu seriálu) a to posílám na tento doplněk ivysilani přes RPC. (Dříve jako parametr play nebo playuri)

U současné verze jsem to zatím nerozchodil. Zkouším to takto:

`xbmc.executeJSONRPC('{"jsonrpc": "2.0", "method": "Addons.ExecuteAddon", "params": {"addonid": "plugin.video.ivysilani.cz", "params": {"action": "play_id", "id": "%s"}}, "id": 1}' % ctId)`

kde jako ID už nejde posílat ID z URL, ale spíš číslo IDEC nebo co to je zač, ale je to vidět v requestech graphql. Co je ale divné, že s ním už to nehodí chybu, ačkoli přehrávání se nespustí, ale akce se vyvolá. Z logu jsem toho moc nevyčetl, žádný error, skoro nic tam není, po cca sekundě od vyvolání je tam jen Closing session to https://ivys-st22-1.o2tv.cz...

Když to shrnu, tak by se zde ideálně hodila nějaká akce nad tímto pluginem, kam bych poslal url ivysilaní a ta už udělala play pořadu dle této URL. Moc zatím ale nevím, co je nejsnadnější cesta pro získání idec (někde jako externalId nebo programId) dle ID v URL. A taky pak, proč se to nepustí. Klidně to napíšu a dám PR, ale potřebuju popostrčit.

Díky. Mám ještě jednu věc, ale tu dám do extra issue.

PS: Napsal bych na fórum, ale nikdo mi tam od víkendu neschválil registraci. Musím tam udělat nějakou akci, aby to někdo odklepl?

**Comment by waladir** [comment]
Ahoj, snad jsem všechno dobře pochopil. Přidat funkci, která spuští přehrávání na základě URL by neměl být problém. Jeho součástí je id a podle něj půjde idec vytáhnout. Nejším ale bude chtít zjistit, proč přehrávání nefunguje. Jestli  je v logu vidět URL streamu, už je to "mimo kontrolu" doplňku. Přehrávání už zajišťuje Kodi resp. InputStream Adaptive. Nevím jestli jsi měl zapnuté Protokolování ladění v nastavení Kodi a jestli by pak v logu nebylo vidět něco víc. Ale zkusím se na to podívat.

**Comment by waladir** [comment]
Pravděpodobně večer sem dám novou verzi, kde bude možné zavolat play_url s parametrem url (URL z webu). Z url se vyextrahuje id, zjisti idec a pustí se přehrávání streamu. Spuštění jsem zkoušel voláním přes curl, kde mi fungovalo:

curl -s -H 'Content-Type: application/json' -d '{"jsonrpc": "2.0", "method": "Player.Open", "params": {"item": { "file" : "plugin://plugin.video.ivysilani.cz/?action=play_url&url=https://www.ceskatelevize.cz/porady/16237-pane-vy-jste-vdova/"}}, "id": 1}' http://localhost:8080/jsonrpc

Klidně můžeš už teď zkusit analogicky pustit stream pres play_id (jako parametr je idec), jestli to tímhle způsobem volání bude vůbec fungovat z Yatse.

**Comment by dimov-cz** [comment]
```
curl -s -H 'Content-Type: application/json' -d '{"jsonrpc": "2.0", "method": "Player.Open", "pa
rams": {"item": { "file" : "plugin://plugin.video.ivysilani.cz/?action=play_url&url=https://www.ceskateleviz
e.cz/porady/16237-pane-vy-jste-vdova/"}}, "id": 1}' http://kodi:kodi@localhost:8080/jsonrpc
```
vede k
```
2024-12-12 08:50:34.740 T:3256    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ValueError'>
                                                   Error Contents: Neznámý parametr: action=play_url&url=https://www.ceskatelevize.cz/porady/16237-pane-vy-jste-vdova/!
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.ivysilani.cz/main.py", line 118, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/storage/.kodi/addons/plugin.video.ivysilani.cz/main.py", line 113, in router
                                                       raise ValueError('Neznámý parametr: {0}!'.format(paramstring))
                                                   ValueError: Neznámý parametr: action=play_url&url=https://www.ceskatelevize.cz/porady/16237-pane-vy-jste-vdova/!
                                                   -->End of Python script error report<--
```
Což bych tedy i čekal, protože v routeru se akce "play_url" neobsluhuje. (Mám tam teď čistou 2.0.7 z repa., CoreElec 20.5) Takže tohle nejde jen mě? Ale pak teda mi ještě uniká, jak by to mělo správně fungova.t

Co ale funguje je 
```
curl -s -H 'Content-Type: application/json' -d '{"jsonrpc": "2.0", "method": "Player.Open", "pa
rams": {"item": { "file" : "plugin://plugin.video.ivysilani.cz/?action=play_id&id=29238360933"}}, "id": 1}'
http://kodi:kodi@localhost:8080/jsonrpc
``` 
Rozdíl byl Player.Open vs Addons.ExecuteAddon. To je super, protože tím se to redukuje na problém toho, jak se cestou nejmenšího odporu dostat z URL k idec.

Díky za popostrčení.

**Comment by waladir** [comment]
Jak jsem psal, verze, kde bude přidaná action play_url, bude nejspíš dnes večer. Zahrnuje víc změn a ještě to potřebuju otestovat. Konkrétně přehrávání přes URL mi ale fungovalo. Pokud ti tedy jede volaní play_id, tak počkej do večera a bude i play_url (ve verzi 2.0.8).

**Comment by dimov-cz** [comment]
Jasný, sorry, měl jsem asi ještě slepený oči, když jsem to četl :) Kdybys nechtěl ještě releasovat, tak můžeš dát dev větev sem a klidně pomůžu s testováním, kdyby se hodilo.

**Comment by waladir** [comment]
Přidáno ve verzi 2.0.8.

**Comment by dimov-cz** [comment]
Funguje to pro pořady, ale pro seriály ne. Ale tam je idec tím druhým id v url. Už jsem si to ošetřil u sebe, pošlu PR. 

Díky za tohle a i za řazení. A taky za rychlost.

**Comment by waladir** [comment]
Díky za PR i donate :-)
