### ISSUE TITLE
Řazení v seznamech

### ISSUE THREAD

**Issue by dimov-cz** [waladir/plugin.video.ivysilani.cz#4]
Mám pocit, že je tam řazení podle počtu zhlédnutí. Je to tak a jde to změnit? 

Já bych to chtěl implicitně od nejnovějších nebo alespoň podle abecedy. Protože jinak když vím, co hledám, tak to tam najít ...no je to na nedeterministické pozici. Zachraňuje to teda fultextové vyhledávání, ale psát na Kodi přes ovladač z gauče není úplně ideál :o)

**Comment by waladir** [comment]
Ahoj, předpokládám, že jde o řazení v kategoriích. Teď se používá výchozí řazení, které je podle podle sledovanosti za poslední týden. V některé z dalších verzí přidám do nastavení vybrat i další alternativy, které API poskytuje - podle abecedy a od nejnovejsich. Jeste je tam pak historicky nejsledovanější, ale to by bylo asi zbytečné.

**Comment by waladir** [comment]
Přidáno ve verzi 2.0.8.
